### ISSUE TITLE
COLMAP ETH3D Results

### ISSUE THREAD

**Issue by travisdriver** [zju3dv/DetectorFreeSfM#19]
Great work, and thank you for open sourcing your code!

Could you provide more details for why the pose AUC values are so low for COLMAP (SIFT + NN) on ETH3D (e.g., did it completely fail on some datasets)? 

The original ETH3D paper (and others) demonstrated that COLMAP performs exceedingly well on these datasets, and the ETH3D ground truth is actually predicated on a COLMAP solution.

**Comment by hxy-123** [comment]
Hi, in the multi-view pose estimation task, COLMAP with SIFT+NN fails in some scenes (a large number of images are missing registration), which leads to poor final scores. 

As for the GT pose generation of ETH3D, [their original paper](https://www.eth3d.net/data/schoeps2017cvpr.pdf) (Sec 3.2) describes that they acquire pose GT by using COLMAP (SIFT+NN) to perform matching between rendered images (using laser scanned geometry) and captured images for initial registration. I think the rendered dense views can reduce the matching difficulty and make the task easier compared with our evaluations.

If I have not overlooked something, the original ETH3D paper seems to only evaluate the COLMAP-MVS part instead of COLMAP-SfM and compare it with other MVS baselines using known GT poses.

**Comment by travisdriver** [comment]
Yes, you're right. I was under the impression that the MVS experiments used the estimated poses as opposed to GT. PixSfM also demonstrated impressive pose estimation results on ETH3D, but they used a specialized evaluation scheme that only used a subset of the images for each dataset. 

Thank you for your response!
