### ISSUE TITLE
How to obtain sparse 3D points with color ?

### ISSUE THREAD

**Issue by lt-xiang** [zju3dv/DetectorFreeSfM#21]
Hi, thanks for your teams' great work.
May I ask how can I get colored sparse 3D spoints ? When I run  Demo data, I can get clomap-format data but visualized 3D potins in colmap-gui are black.

![image](https://github.com/zju3dv/DetectorFreeSfM/assets/27660078/c1b66d70-ea94-40c0-a60a-8aaf4fc21ea1)

**Comment by hxy-123** [comment]
Hi, it seems that this is not the result of our demo data. I'm sure the produced point cloud using demo data with readme's instruction has color. You can try it first to see whether it works well. Moreover, we note that the L22 in [demo config](https://github.com/zju3dv/DetectorFreeSfM/blob/55efcc216f449850d36e95835c454c41c4e71cd4/hydra_configs/demo/dfsfm.yaml#L22) needs to be specified to **your absolute path to data** so that the color can be extracted.

**Comment by hypochlorous** [comment]
@lt-xiang Excuse me. I want to run this work on my custom datasets, what settings should I change?
And how can i convert the bin file to txt format?
